{
  tokens=[
      space="regexp:\s+"
      POPEN="("
      PCLOSED=")"
      COMMA=","
      ATR_OP="="
      id='regexp:[a-zA-Z_][a-zA-Z_0-9]*'

      octnum='regexp:0[0-7]+'
      decnum='regexp:[1-9][0-9]*'
      hexnum='regexp:0x[a-fA-F0-9]+'
  ]
}

// function call
function_call ::= id "(" [func_args] ")"
func_args ::= positional_args ["," kw_args] | kw_args

// postional args
positional_args ::= positional_arg ("," positional_arg)*
positional_arg ::= expression

// kwargs
kw_args ::= kw_arg ("," kw_arg)*
kw_arg ::= id "=" expression

// expressions
expression ::= id | octnum_literal | decnum_literal | hexnum_literal
octnum_literal ::= octnum
decnum_literal ::= decnum
hexnum_literal ::= hexnum
